version: "3.8"

services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_fc_ecommerce
#      - SPRING_DATASOURCE_USERNAME=ecommerce_user
#      - SPRING_DATASOURCE_PASSWORD=@pguser123
#    depends_on:
#      - db
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=db_fc_ecommerce
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=@pguser123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecommerce_user -d db_fc_ecommerce" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: